import REGENERATED_STORY_IMAGE from "./assets/images/regenerated_image_1790539590288.jpg";

export const AGRI_IMAGES = {
  HERO: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&q=80&w=2600",
  BIO_HERO: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&q=80&w=2600",
  STORY: REGENERATED_STORY_IMAGE,
  STORY_HERO: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=2600",
  SOIL_FARM: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&q=80&w=1000",
  GREENHOUSE: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=1000",
  IRRIGATION: "https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&q=80&w=1000",
  CROP_HARVEST: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&q=80&w=1000",
  BIO_NUTRIENTS: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&q=80&w=1000",
  BIO_FUNGICIDES: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=1000",
  HEIRLOOM_SEEDS: "https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&q=80&w=1000",
  TISSUE_CULTURE: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1000",
  SEAWEED_FERTILIZER: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&q=80&w=1000",
};

export const HERITAGE_IMAGES = AGRI_IMAGES;

export const MOCK_AGRI_IMAGES = [
  "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800",
];

export const MOCK_PRODUCTS = [
  {
    id: "agri-1",
    name: "Cauvery Bio-Gold Organic NPK Concentrate",
    subtitle: "Enriched Bio-Nutrients for Soil Health & Crop Yield",
    description: "Pure microbial soil revitalizer packed with nitrogen fixers, phosphate solubilizers, and humic extracts from the Cauvery Delta.",
    price: 1250,
    category: "Nutrients",
    imageUrls: [MOCK_AGRI_IMAGES[0]],
    isFeatured: true,
    isBestSeller: true,
    stock: 45,
    createdAt: new Date(),
  },
  {
    id: "agri-2",
    name: "NeemShield Botanical Bio-Fungicide",
    subtitle: "Pure Cold-Pressed Neem Oil & Trichoderma Formulation",
    description: "100% natural organic fungicide and disease protection agent targeting leaf rust, mildew, and soil-borne fungal pathogens.",
    price: 850,
    category: "Fungicides",
    imageUrls: [MOCK_AGRI_IMAGES[1]],
    isNew: true,
    stock: 60,
    createdAt: new Date(),
  },
  {
    id: "agri-3",
    name: "Native Heirloom Paddy Seeds (Mapillai Samba)",
    subtitle: "Drought-Resistant High-Nutrition Heirloom Grain",
    description: "Certified organic Tamil Nadu heritage rice seeds harvested directly from native seed conservation farms.",
    price: 1800,
    category: "Seeds",
    imageUrls: [MOCK_AGRI_IMAGES[2]],
    isFeatured: true,
    stock: 25,
    createdAt: new Date(),
  },
  {
    id: "agri-4",
    name: "Banana Tissue Culture Plantlets (Grand Naine)",
    subtitle: "High-Yield Disease-Free Laboratory Plantlets",
    description: "Virus-free tissue culture banana plantlets prepared in sterile bio-chambers for accelerated growth and maximum bunch yield.",
    price: 3200,
    category: "Tissue Culture",
    imageUrls: [MOCK_AGRI_IMAGES[3]],
    isNew: true,
    stock: 30,
    createdAt: new Date(),
  },
  {
    id: "agri-5",
    name: "Bio-Power Natural Seaweed Liquid Fertilizer",
    subtitle: "100% Organic Cold-Extracted Ascophyllum Nodosum",
    description: "Foliar spray booster rich in natural cytokinins and micro-nutrients for flower setting and root development.",
    price: 950,
    category: "Fertilizers",
    imageUrls: [MOCK_AGRI_IMAGES[4]],
    isBestSeller: true,
    stock: 50,
    createdAt: new Date(),
  },
  {
    id: "agri-6",
    name: "Drip Irrigation Micro-Sprinkler Hardware Kit",
    subtitle: "Precision Agricultural Water-Saving Irrigation Set",
    description: "Durable UV-stabilized agricultural drip emitters, pressure regulators, and micro-tubing for efficient crop hydration.",
    price: 2400,
    category: "Hardware",
    imageUrls: [MOCK_AGRI_IMAGES[0]],
    isNew: true,
    stock: 15,
    createdAt: new Date(),
  },
  {
    id: "agri-7",
    name: "Organic Neem Seed Cake Bio-Insecticide",
    subtitle: "Eco-Friendly Root Pest Control & Soil Conditioner",
    description: "Cold-pressed neem cake pellets that eradicate nematodes and soil pests while providing slow-release organic nitrogen.",
    price: 1100,
    category: "Insecticides",
    imageUrls: [MOCK_AGRI_IMAGES[1]],
    isBestSeller: true,
    stock: 40,
    createdAt: new Date(),
  },
];
